### ISSUE TITLE
[WIKI] hello-world wiki outdated

### ISSUE THREAD

**Issue by berendeanicolae** [MAYHEM-Lab/cspot#42]
Hello,

For the hello-world app, it's also necessary to include an -W argument. I've updated the workflow with the argument: https://github.com/berendeanicolae/cspot-wiki/blob/hw-wiki/Home.md
Unfortunately, the wiki cannot be updated via pull requests. 

Thanks,
Nicolae

**Comment by richwolski** [comment]
should be fixed now.
